# Generated by Django 4.2.29 on 2026-03-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
