# Generated by Django 4.2.28 on 2026-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('time', models.DateTimeField(default='2026-02-17 10:41:03.735949')),
            ],
        ),
    ]
