# Generated by Django 4.2.28 on 2026-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='time',
            field=models.DateTimeField(default='2026-02-17 10:41:17.954717'),
        ),
    ]
