# Generated by Django 4.2.17 on 2026-02-15 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 15, 14, 52, 23, 216897), verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
