# Generated by Django 4.2.28 on 2026-02-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex02', '0002_alter_text_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='time',
            field=models.DateTimeField(default='2026-02-17 10:42:06.562583'),
        ),
    ]
