# Generated by Django 4.2.17 on 2026-03-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Planets',
        ),
    ]
