# Generated by Django 4.2.17 on 2026-03-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ex09', '0004_delete_people_delete_planets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.TextField(blank=True, null=True)),
                ('diameter', models.PositiveIntegerField(blank=True, null=True)),
                ('orbital_period', models.PositiveIntegerField(blank=True, null=True)),
                ('population', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rotation_period', models.PositiveIntegerField(blank=True, null=True)),
                ('surface_water', models.FloatField(blank=True, null=True)),
                ('terrain', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('birth_year', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(max_length=32)),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=32, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('homeworld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ex09.planets', to_field='name')),
            ],
        ),
    ]
