# Generated by Django 4.2.28 on 2026-02-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
