# Generated by Django 4.2.28 on 2026-02-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
