# Generated by Django 4.2 on 2026-05-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
