# Generated by Django 4.2 on 2026-05-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_tip_downvote_tip_upvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.user')),
            ],
        ),
    ]
