# Generated by Django 4.2 on 2026-05-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(),
        ),
    ]
