# Generated by Django 4.2 on 2026-05-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0006_alter_vote_user_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_dowmvote', 'Can Downvote a Tip!')]},
        ),
    ]
