# Generated by Django 4.2 on 2026-05-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0008_alter_tip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={},
        ),
    ]
