# Generated by Django 4.2 on 2026-05-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0009_alter_tip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_downvote', 'Can Downvote a Tip!')]},
        ),
    ]
