# Generated by Django 4.2 on 2026-05-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0011_user_alter_vote_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={},
        ),
    ]
