# Generated by Django 4.2 on 2026-05-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0012_alter_tip_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permissions', models.ManyToManyField(to='ex.perm')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='perm',
            field=models.ManyToManyField(blank=True, to='ex.perm'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, to='ex.role'),
        ),
    ]
