# Generated by Django 4.2 on 2026-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0014_alter_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(default=None, to='ex.perm'),
        ),
    ]
