# Generated by Django 4.2 on 2026-05-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0015_alter_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
